Update Catch2 2.1.2 to 2.13.10
This was necessary because of the following error with clang 16.0.6:

    ../lib/catch/include/catch/catch.hpp:7320:33:
    error: variable length array declaration not allowed at file scope
    char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};